version: '3'
services:

  mariadb:
    image: 'mariadb:10.11.2'
    hostname: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network
    restart: unless-stopped

  hive-metastore:
    image: 'custom-hive-metastore'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network
    restart: unless-stopped

  trino:
    image: trinodb/trino:410
    hostname: trino_container
    ports:
      - 8080:8080
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    networks:
      - trino-network
    depends_on:
      - minio
      - hive-metastore
    restart: unless-stopped


  minio:
    image: minio/minio:RELEASE.2023-08-31T15-31-16Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test12334567
    command: server /data --console-address ":9001"
    networks:
      - trino-network
    restart: unless-stopped

volumes:
  trino:
    driver: local
  conf:
    driver: local
  minio-data:
    driver: local

networks:
  trino-network:
    driver: bridge


